### ISSUE TITLE
Add test setup using react-hooks-testing-library

### ISSUE THREAD

**Issue by bendtherules** [Hermanya/create-react-hook#11]
Consider adding react-hooks-testing-library for testing custom hooks separately - sort of like unit tests. This should be part of src/tests.
Examples folder can be kept for demo purpose and integration testing

**Comment by Hermanya** [comment]
I have been thinking about it, but haven't had the time. PR welcome!

**Comment by bendtherules** [comment]
Great. I'll give it a try.

**Comment by bendtherules** [comment]
So, just to clarify - are you currently running travis ci on the hooks that you made with this lib?
Couldn't find public builds with your username there.

In my repo, travis tests are failing on node 9 - because typescript-eslint doesn't seem to support that specific version. With node 8, 10, 11 - everything is fine.
Do you know a workaround for this? I just removed 9 from travis node versions for now.

**Comment by Hermanya** [comment]
create-react-hook is based on create-react-library, and I'm guessing since the fork travis has removed support for that node version.
I don't even have travis ci set up in this repo :D

**Comment by bendtherules** [comment]
> create-react-hook is based on create-react-library, and I'm guessing since the fork travis has removed support for that node version.

No, its not because of travis itself. Ex: https://travis-ci.org/bendtherules/some-hooks/jobs/631280716 .
@typescript-eslint/eslint-plugin doesn't seem to support node 9 specifically.

**Comment by bendtherules** [comment]
Added a PR for this. #12
