### ISSUE TITLE
Permission issue when use create react hook script

### ISSUE THREAD

**Issue by ZengLawrence** [Hermanya/create-react-hook#14]
I ran into 2 problems while using this create script on Mac:
1. I had to use "sudo" to run the script because it made a symlink to \.npm folder (global one on Mac).
2. Because of above, local git repository was created with a root permission, which cause any update to local repository to fail due to permission issue.  I had to delete \.git folder and clone directly from my remote repository.  Can you add an option and warning to skip git repository creation?

Thanks
Lawrence

**Comment by Hermanya** [comment]
This is not a problem I had, or have had anybody report. Is your node installation okay? I know sometimes you need sudo if your node is installed incorrectly. What symlink did it make exactly?

**Comment by ZengLawrence** [comment]
Nodejs was installed with downloaded Mac package from nodejs.org website.  I reinstalled it again today and got same error.

Here is the partial stack trace from today:
```bash
✖ Running npm install and npm link
Error: Command failed: /bin/sh -c npm link
npm ERR! code EACCES
npm ERR! syscall symlink
npm ERR! path /Users/lawrencezeng/vscode/test-hook
npm ERR! dest /usr/local/lib/node_modules/test-hook
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, symlink '/Users/lawrencezeng/vscode/test-hook' -> '/usr/local/lib/node_modules/test-hook'
```
I have not tried to use a version manager for npm.  It might make a difference.

**Comment by Hermanya** [comment]
https://stackoverflow.com/questions/47252451/permission-denied-when-installing-npm-modules-in-osx

Try installing node with Homebrew. Or better yet try nvm

**Comment by ZengLawrence** [comment]
Using 'nvm' resolved the permission with npm.  However, git was not setup properly.  I couldn't push to my remote repository and had to following instructions in this [StackOverflow](https://stackoverflow.com/questions/2411031/how-do-i-clone-into-a-non-empty-directory) to correct the git setup.
