### ISSUE TITLE
Add useMarked() hook

### ISSUE THREAD

**Issue by this-fifo** [Hermanya/create-react-hook#16]
Hey @Hermanya , thanks a lot for this sweet cli, made my life so much easier and it was fun to play with

wanted to contribute and add a custom hook I made for my own needs

https://github.com/this-fifo/use-marked-hook
https://www.npmjs.com/package/use-marked-hook

feel free to add it to the list if you wish :)

**Comment by Hermanya** [comment]
Cool! Added
