### ISSUE TITLE
keep on npm install 

### ISSUE THREAD

**Issue by 34678** [Hermanya/create-react-hook#20]
help
when i init the project,it keep on npm installing,and i can see the progress~
![image](https://user-images.githubusercontent.com/23259141/75106397-05f04f80-5657-11ea-9646-f3d5b166e3d0.png)

**Comment by taystack** [comment]
Same for the `yarn` option.

**Comment by Hermanya** [comment]
I think this is resolved in v3.0.2 by https://github.com/Hermanya/create-react-hook/pull/21
