### ISSUE TITLE
dist/index.d.ts is not exportable in typescript template

### ISSUE THREAD

**Issue by elzup** [Hermanya/create-react-hook#22]
ts user needs `dist/index.d.ts`.

ts template's package.json does not include "files".

```
  "files": [
    "dist"
  ],
```
everyone finally adds the option to package.json by typescript module.

https://github.com/Hermanya/use-interval/blob/master/package.json#L50
https://github.com/Hermanya/use-typing-effect/blob/master/package.json#L48

also me https://github.com/elzup/use-seconds/blob/master/package.json#L11

**Comment by Hermanya** [comment]
The problem is that other files in that directory will be ignored when I publish create-react-hook. Nesting package.jsons is problematic. But there must be a way to do it

**Comment by fulviocanducci** [comment]
I resolved it as follows:

@Hermanya and @elzup 
```js
"files": [
    "dist/"
],
```
in the file `package.json`

**Comment by elzup** [comment]
ok. It's a Proposal. My project has no problem.
packages.json does not include "files" property by create-react-app project-name --typescript`
Wouldn't it be nice for TypeScript library developers in most cases?

> The problem is that other files in that directory will be ignored when I publish create-react-hook.
Does it affect "gh-pages" sample project deploy? It is better to deploy the module.

**Comment by Hermanya** [comment]
I agree it would be nice if created projects had that setting by default. What I'm saying is I don't know how to make it work. If I add that setting into templates here, then I won't be able to publish create-react-hook on npm, because it's not going to include all files. I'm sure there is a way around that, but I don't know what it is.

**Comment by fulviocanducci** [comment]
> I agree it would be nice if created projects had that setting by default. What I'm saying is I don't know how to make it work. If I add that setting into templates here, then I won't be able to publish create-react-hook on npm, because it's not going to include all files. I'm sure there is a way around that, but I don't know what it is.


How is the create-react-hook package.json file created for the Typescript template?

**Comment by Hermanya** [comment]
It's copied from https://github.com/Hermanya/create-react-hook/blob/master/template/typescript/package.json

**Comment by fulviocanducci** [comment]
> It's copied from https://github.com/Hermanya/create-react-hook/blob/master/template/typescript/package.json


Wouldn't a variable like that in `{{name}}` solve automatically?

**Comment by Hermanya** [comment]
it might :)
