### ISSUE TITLE
Add use-reducer-with-effects

### ISSUE THREAD

**Issue by frankiesardo** [Hermanya/create-react-hook#30]
Just created this hook using you library https://github.com/frankiesardo/use-reducer-with-effects

It was incredibly simple, thanks for your work!

**Comment by Hermanya** [comment]
added 👍

**Comment by Hermanya** [comment]
do you know about https://github.com/conorhastings/use-reducer-with-side-effects?

**Comment by frankiesardo** [comment]
Thank you @Hermanya . I has a look at it and it's a solid library. Unfortunately the side effects are stored as functions while I prefer everything to be pure data so I still think my library still has a reason for existing 😃
